// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gofr "gofr.dev/pkg/gofr"
)

// MockDeploymentSpaceService is a mock of DeploymentSpaceService interface.
type MockDeploymentSpaceService struct {
	ctrl     *gomock.Controller
	recorder *MockDeploymentSpaceServiceMockRecorder
}

// MockDeploymentSpaceServiceMockRecorder is the mock recorder for MockDeploymentSpaceService.
type MockDeploymentSpaceServiceMockRecorder struct {
	mock *MockDeploymentSpaceService
}

// NewMockDeploymentSpaceService creates a new mock instance.
func NewMockDeploymentSpaceService(ctrl *gomock.Controller) *MockDeploymentSpaceService {
	mock := &MockDeploymentSpaceService{ctrl: ctrl}
	mock.recorder = &MockDeploymentSpaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeploymentSpaceService) EXPECT() *MockDeploymentSpaceServiceMockRecorder {
	return m.recorder
}

// AddDeploymentSpace mocks base method.
func (m *MockDeploymentSpaceService) AddDeploymentSpace(ctx *gofr.Context, deploymentSpace *DeploymentSpace, environmentID int) (*DeploymentSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeploymentSpace", ctx, deploymentSpace, environmentID)
	ret0, _ := ret[0].(*DeploymentSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDeploymentSpace indicates an expected call of AddDeploymentSpace.
func (mr *MockDeploymentSpaceServiceMockRecorder) AddDeploymentSpace(ctx, deploymentSpace, environmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeploymentSpace", reflect.TypeOf((*MockDeploymentSpaceService)(nil).AddDeploymentSpace), ctx, deploymentSpace, environmentID)
}

// FetchDeploymentSpace mocks base method.
func (m *MockDeploymentSpaceService) FetchDeploymentSpace(ctx *gofr.Context, environmentID int) (*DeploymentSpaceResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDeploymentSpace", ctx, environmentID)
	ret0, _ := ret[0].(*DeploymentSpaceResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDeploymentSpace indicates an expected call of FetchDeploymentSpace.
func (mr *MockDeploymentSpaceServiceMockRecorder) FetchDeploymentSpace(ctx, environmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDeploymentSpace", reflect.TypeOf((*MockDeploymentSpaceService)(nil).FetchDeploymentSpace), ctx, environmentID)
}
